language: node_js
cache: yarn
node_js: '8'
before_deploy:
  - npm run build
script: yarn lint && yarn build
deploy:
  provider: heroku
  api_key:
    secure: 019c8508-2e9a-4090-8638-6f08931a7e1a
  app: expense-tracker-todo
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
    repo: ReginaGimazova/expenseTracker
