language: node_js
cache:
  yarn: true
  directories:
    - node-modules
node_js: '8'
before_deploy:
  - npm run build
script: yarn build
deploy:
  provider: heroku
  api_key:
    secure: 019c8508-2e9a-4090-8638-6f08931a7e1a
  app: expense-tracker-todo
  on:
    branch: master
    repo: ReginaGimazova/expenseTracker
