language: node_js
node_js: node

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: deploy
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
