language: node_js
node_js: node

before_deploy:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: build
  github-token: $GITHUB_TOKEN
  github-url: https://reginagimazova.github.io/expenseTracker/
  keep-history: true
  on:
    branch: master
