language: node_js
cache:
  directories:
    - node_modules
node_js: node

before_deploy:
  - npm run build

deploy:
  provider: heroku
  api_key:
    secure: 019c8508-2e9a-4090-8638-6f08931a7e1a
  app: expense-tracker-todo
  skip-cleanup: true
  local_dir: build
  keep-history: true
  on:
    branch: master
    repo: ReginaGimazova/expenseTracker
